import Head from "next/head";
import React, { useState } from "react";
import Modal from "../components/global/modal/Modal";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const openModal = () => {
    setIsOpen(true);
  };

  const closeModal = () => {
    setIsOpen(false);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen flex items-center justify-center">
        <Modal isOpen={isOpen} closeModal={closeModal} />
        <button className="bg-red-400 py-5 px-16" onClick={openModal}>
          {" "}
          Click Me
        </button>
      </div>
      <div className="h-screen"></div>
      <div className="h-screen"></div>
    </>
  );
}
